<?php
/**
 * StoreRestrictions
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Baluwo External API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.27
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;
use \Swagger\Client\ObjectSerializer;

/**
 * StoreRestrictions Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class StoreRestrictions implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'StoreRestrictions';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'min_order_amount_eur' => 'double',
        'max_order_amount_eur' => 'double',
        'max_order_quantity' => 'int'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'min_order_amount_eur' => 'double',
        'max_order_amount_eur' => 'double',
        'max_order_quantity' => 'int32'
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'min_order_amount_eur' => 'minOrderAmountEUR',
        'max_order_amount_eur' => 'maxOrderAmountEUR',
        'max_order_quantity' => 'maxOrderQuantity'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'min_order_amount_eur' => 'setMinOrderAmountEur',
        'max_order_amount_eur' => 'setMaxOrderAmountEur',
        'max_order_quantity' => 'setMaxOrderQuantity'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'min_order_amount_eur' => 'getMinOrderAmountEur',
        'max_order_amount_eur' => 'getMaxOrderAmountEur',
        'max_order_quantity' => 'getMaxOrderQuantity'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['min_order_amount_eur'] = isset($data['min_order_amount_eur']) ? $data['min_order_amount_eur'] : null;
        $this->container['max_order_amount_eur'] = isset($data['max_order_amount_eur']) ? $data['max_order_amount_eur'] : null;
        $this->container['max_order_quantity'] = isset($data['max_order_quantity']) ? $data['max_order_quantity'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets min_order_amount_eur
     *
     * @return double
     */
    public function getMinOrderAmountEur()
    {
        return $this->container['min_order_amount_eur'];
    }

    /**
     * Sets min_order_amount_eur
     *
     * @param double $min_order_amount_eur min_order_amount_eur
     *
     * @return $this
     */
    public function setMinOrderAmountEur($min_order_amount_eur)
    {
        $this->container['min_order_amount_eur'] = $min_order_amount_eur;

        return $this;
    }

    /**
     * Gets max_order_amount_eur
     *
     * @return double
     */
    public function getMaxOrderAmountEur()
    {
        return $this->container['max_order_amount_eur'];
    }

    /**
     * Sets max_order_amount_eur
     *
     * @param double $max_order_amount_eur max_order_amount_eur
     *
     * @return $this
     */
    public function setMaxOrderAmountEur($max_order_amount_eur)
    {
        $this->container['max_order_amount_eur'] = $max_order_amount_eur;

        return $this;
    }

    /**
     * Gets max_order_quantity
     *
     * @return int
     */
    public function getMaxOrderQuantity()
    {
        return $this->container['max_order_quantity'];
    }

    /**
     * Sets max_order_quantity
     *
     * @param int $max_order_quantity max_order_quantity
     *
     * @return $this
     */
    public function setMaxOrderQuantity($max_order_quantity)
    {
        $this->container['max_order_quantity'] = $max_order_quantity;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


