<?php
/**
 * ExternalPromotionDescriptionDtoTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Baluwo External API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.27
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * ExternalPromotionDescriptionDtoTest Class Doc Comment
 *
 * @category    Class
 * @description ExternalPromotionDescriptionDto
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ExternalPromotionDescriptionDtoTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ExternalPromotionDescriptionDto"
     */
    public function testExternalPromotionDescriptionDto()
    {
    }

    /**
     * Test attribute "provider_code"
     */
    public function testPropertyProviderCode()
    {
    }

    /**
     * Test attribute "start_utc"
     */
    public function testPropertyStartUtc()
    {
    }

    /**
     * Test attribute "end_utc"
     */
    public function testPropertyEndUtc()
    {
    }

    /**
     * Test attribute "currency_iso"
     */
    public function testPropertyCurrencyIso()
    {
    }

    /**
     * Test attribute "minimum_send_amount"
     */
    public function testPropertyMinimumSendAmount()
    {
    }

    /**
     * Test attribute "dates"
     */
    public function testPropertyDates()
    {
    }

    /**
     * Test attribute "headline"
     */
    public function testPropertyHeadline()
    {
    }

    /**
     * Test attribute "terms_and_conditions"
     */
    public function testPropertyTermsAndConditions()
    {
    }

    /**
     * Test attribute "bonus_validity"
     */
    public function testPropertyBonusValidity()
    {
    }
}
