<?php
/**
 * OrderRestrictionsTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Baluwo External API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.27
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * OrderRestrictionsTest Class Doc Comment
 *
 * @category    Class
 * @description OrderRestrictions
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class OrderRestrictionsTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "OrderRestrictions"
     */
    public function testOrderRestrictions()
    {
    }

    /**
     * Test attribute "min_cash_power_order_amount_eur"
     */
    public function testPropertyMinCashPowerOrderAmountEur()
    {
    }

    /**
     * Test attribute "max_cash_power_order_amount_eur"
     */
    public function testPropertyMaxCashPowerOrderAmountEur()
    {
    }

    /**
     * Test attribute "min_air_time_order_amount_eur"
     */
    public function testPropertyMinAirTimeOrderAmountEur()
    {
    }

    /**
     * Test attribute "max_air_time_order_amount_eur"
     */
    public function testPropertyMaxAirTimeOrderAmountEur()
    {
    }

    /**
     * Test attribute "min_bill_order_amount_eur"
     */
    public function testPropertyMinBillOrderAmountEur()
    {
    }

    /**
     * Test attribute "max_bill_order_amount_eur"
     */
    public function testPropertyMaxBillOrderAmountEur()
    {
    }

    /**
     * Test attribute "min_gift_card_order_amount_eur"
     */
    public function testPropertyMinGiftCardOrderAmountEur()
    {
    }

    /**
     * Test attribute "max_gift_card_order_amount_eur"
     */
    public function testPropertyMaxGiftCardOrderAmountEur()
    {
    }

    /**
     * Test attribute "food_restrictions"
     */
    public function testPropertyFoodRestrictions()
    {
    }

    /**
     * Test attribute "construction_restrictions"
     */
    public function testPropertyConstructionRestrictions()
    {
    }

    /**
     * Test attribute "fabric_restrictions"
     */
    public function testPropertyFabricRestrictions()
    {
    }

    /**
     * Test attribute "ram_restrictions"
     */
    public function testPropertyRamRestrictions()
    {
    }
}
