<?php
/**
 * StoreRestrictionsTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Baluwo External API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.27
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * StoreRestrictionsTest Class Doc Comment
 *
 * @category    Class
 * @description StoreRestrictions
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class StoreRestrictionsTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "StoreRestrictions"
     */
    public function testStoreRestrictions()
    {
    }

    /**
     * Test attribute "min_order_amount_eur"
     */
    public function testPropertyMinOrderAmountEur()
    {
    }

    /**
     * Test attribute "max_order_amount_eur"
     */
    public function testPropertyMaxOrderAmountEur()
    {
    }

    /**
     * Test attribute "max_order_quantity"
     */
    public function testPropertyMaxOrderQuantity()
    {
    }
}
